name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev || uv pip install -e .
    
    - name: Lint with ruff
      run: |
        uv run ruff check .
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
    
    - name: Format check with black
      run: |
        uv run black --check .
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
    
    - name: Type check with mypy
      run: |
        uv run mypy src/eyelet
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      continue-on-error: true
    
    - name: Test with pytest
      run: |
        uv run pytest tests/ -v --cov=eyelet --cov-report=xml || echo "Tests not yet implemented"
      continue-on-error: true
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true
    
    - name: Build package
      run: |
        uv build
    
    - name: Test installation
      run: |
        uv pip install dist/*.whl
        uv run eyelet --version
        uv run eyelet validate settings --help